name: hive_benchmark

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.5.1
  path: ^1.6.4
  random_string: ^1.1.0
  hive: ^1.3.0
  sqflite: ^1.2.0
  shared_preferences: ^0.5.6
  fl_chart: ^0.1.6
  moor_ffi: ^0.3.1

flutter:
  uses-material-design: true